SELECT D_FName, D_LName FROM DOCTORS, APPOINTMENTS where (DOCTORS.Doctor_Id = APPOINTMENTS.Doctor_Id AND APPOINTMENTS.Patient_Id = 4);

SELECT D_FName, D_LName FROM DOCTORS WHERE Doctor_Id = 
(SELECT Doctor_Id FROM APPOINTMENTS GROUP BY Doctor_Id HAVING count(Doctor_Id) =
 ((SELECT MAX(DCOUNT) FROM (SELECT COUNT(Doctor_Id) AS DCOUNT 
FROM APPOINTMENTS Group By Doctor_Id ) AS MAXCOUNT )));

UPDATE PRESCRIPTIONS SET Picked_Up_Date = now()::DATE WHERE (MedName = 'Paracetamol' AND Picked_Up_Date IS NULL);

SELECT MedName, (sum(Dosage)*sum(Duration)) AS Quantity FROM PRESCRIPTIONS,PATIENTS WHERE PATIENTS.Patient_Id = 
PRESCRIPTIONS.Patient_Id AND PATIENTS.P_City = 
'Bengaluru' GROUP BY MedName;

SELECT P_FName, P_LName, P_PhNo, TimeIn FROM 
PATIENTS, APPOINTMENTS WHERE PATIENTS.Patient_Id = APPOINTMENTS.Patient_Id AND DATE = NOW()::DATE AND Doctor_Id = 4;

